FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    jq \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN python3 -m venv /app/venv

ENV PATH="/app/venv/bin:$PATH"
ENV PYTHONUNBUFFERED=1

RUN pip install fastapi==0.136.1 uvicorn==0.47.0 pandas==3.0.3 kubernetes==35.0.0

COPY src/api/stockflow_controller.py /app/stockflow_controller.py

CMD ["python3","stockflow_controller.py"]